version: '3.7'
x-build: &build
  build:
    context: .
    cache_from:
      - eshelf
      - quay.io/nyulibraries/eshelf
      - quay.io/nyulibraries/eshelf:$BRANCH_NO_SLASH
  image: eshelf
  tty: true
  stdin_open: true
x-test-env: &test-env
  <<: *build
  environment:
    RAILS_ENV: test
    ESHELF_DB_DATABASE: eshelf_test
    BRANCH_NO_SLASH:
    CI:
    CODECLIMATE_REPO_TOKEN:
    COVERALLS_REPO_TOKEN:
  env_file:
    - test.env
x-dev-env: &dev-env
  <<: *build
  env_file:
    - test.env

services:
  dev:
    <<: *dev-env
    ports:
      - "3000:3000"
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
    depends_on:
      - setup_dbs
    # external_links:
    #   - push_to_cite_dev_1:pushtocite
    # networks:
    #   - default
    #   - custom
    # volumes:
    #   - .:/app

  # docker-compose run test ruby -Itest ./test/unit/decorators/label_decorator_test.rb --name test_label_notes
  test:
    <<: *test-env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake"]
    depends_on:
      - setup_test_dbs
    # external_links:
    #   - push_to_cite_dev_1:pushtocite
    # networks:
    #   - default
    #   - custom
    # volumes:
    #   - .:/app

  setup_test_dbs:
    <<: *test-env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake", "db:setup"]
    depends_on:
      - db

  setup_dbs:
    <<: *dev-env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake", "db:setup"]
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    expose:
      - "3306"

# networks:
#   custom:
#     external: true