version: '3.7'
x-volumes: &default-volumes
  volumes:
    - ./lib:/app/lib/
    - ./app:/app/app/
    - ./spec:/app/spec/
    - ./test:/app/test/
    - ./Rakefile:/app/Rakefile
    - ./tmp/:/app/tmp/

x-production: &production-image
  build:
    context: .
    cache_from:
    - eshelf
    - quay.io/nyulibraries/eshelf
    - quay.io/nyulibraries/eshelf:$BRANCH_NO_SLASH
  image: eshelf:latest

x-development: &development-image
  build:
    context: .
    cache_from:
    - eshelf_test
    - quay.io/nyulibraries/eshelf_test
    - quay.io/nyulibraries/eshelf_test:$BRANCH_NO_SLASH
    dockerfile: Dockerfile.test
  image: eshelf_test:latest

services:
  dev:
    <<: *development-image
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
    depends_on:
      - setup_dev_dbs
    env_file:
      - test.env
    # <<: *default-volumes

  # docker-compose run test ruby -Itest ./test/unit/decorators/label_decorator_test.rb --name test_label_notes
  test:
    <<: *development-image
    tty: true
    stdin_open: true
    shm_size: '1g'
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "bundle", "exec", "rake"]
    depends_on:
      - setup_test_dbs
    environment:
      RAILS_ENV: test
      CI:
      CODECLIMATE_REPO_TOKEN:
      COVERALLS_REPO_TOKEN:
    env_file:
      - test.env
    # <<: *default-volumes
  
  # Use below settings for testing unicorn image locally
  unicorn:
    <<: *production-image
    command: ["./script/start.sh", "production"]
    ports:
      - "5000:5000"
    env_file:
      - test.env
    environment:
      UNICORN_PORT: 5000
      RAILS_LOG_LEVEL: debug
    depends_on:
      - setup_dev_dbs

  setup_test_dbs:
    <<: *development-image
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "bundle", "exec", "rake", "db:setup"]
    depends_on:
      - db

  setup_dev_dbs:
    <<: *development-image
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "bundle", "exec", "rake", "db:setup"]
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    expose:
      - "3306"
