version: '3.2'
services:

  dev:
    # These options (tty, stdin_open) let you interact with pry with
    # docker attach {running_dev_container_id}
    tty: true
    stdin_open: true
    image: eshelf_dev
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
    depends_on:
      - setup_dbs

  test:
    tty: true
    stdin_open: true
    image: eshelf_test
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      RAILS_ENV: test
      CI:
      CODECLIMATE_REPO_TOKEN:
      COVERALLS_REPO_TOKEN:
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake"]
    depends_on:
      - setup_test_dbs

  setup_test_dbs:
    image: eshelf_test
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake", "db:setup"]
    depends_on:
      - db

  setup_dbs:
    image: eshelf_dev
    build: .
    environment:
      RAILS_ENV: development
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake", "db:setup"]
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    expose:
      - "3306"
