# This file is only used for dev/test purposes
# the actual IP config lives on a K8s config
<% DEFAULT_INSTITUTIONS = {'NYU' => {'ip_addresses' => ['127.0.0.1']}} unless defined?(DEFAULT_INSTITUTIONS) %>
<%= DEFAULT_INSTITUTIONS.to_yaml %>
